platform :ios, '7.0'
xcodeproj 'OPDBit.xcodeproj'

pod 'KVNProgress', '2.1.9'
pod 'AFNetworking', '2.5.1'
pod 'Realm', '0.90.6'
pod 'HMSegmentedControl', '1.5'
pod 'Masonry', '0.6.1'
pod 'MMDrawerController', '0.5.7'
pod 'RMDateSelectionViewController', '1.4.3'
pod 'MZClockView', '1.0.2'
